Repository ITU-BDSA2024-GROUP10/Chirp, pull requests merged in 2024-09, with the labels that each got.

#12 User interface refactor
  Program.cs
  UserInterface.cs
Labels: refactor

#13 CLI Package Integration
  Chirp.CLI.csproj
  Program.cs
Labels: refactor

#37 Refactor program cheep and csvdatabase
  Chirp/.idea/.idea.Chirp/.idea/indexLayout.xml
  Chirp/data/chirp_cli_db.csv
  Chirp/src/Chirp.CLI.Client/Cheep.cs
  Chirp/src/Chirp.CLI.Client/CheepMap.cs
  Chirp/src/Chirp.CLI.Client/Program.cs
  Chirp/src/SimpleDB/CsvDatabase.cs
Labels: refactor

#44 Giving action permetion to write
  .github/workflows/automatic-release.yml
Labels: bug

#46 Work flow test
  .github/workflows/build-and-test.yaml
  THIS_IS_A_TEMP_FILE_FOR_WORKFLOW_TEST
Labels: feature

#48 Update build for all platforms
  .github/workflows/automatic-release.yml
Labels: bug

#49 Updated zipping
  .github/workflows/automatic-release.yml
Labels: bug

#50 Update publish
  .github/workflows/automatic-release.yml
Labels: bug

#51 Updated working dirrectory
  .github/workflows/automatic-release.yml
Labels: bug

#52 Update zip file path for Release
  .github/workflows/automatic-release.yml
Labels: bug

#53 Update debug for relase auto incrementing
  .github/workflows/automatic-release.yml
Labels: bug

#54 Extracted out getting the label to update the release
  .github/workflows/automatic-release.yml
Labels: bug

#55 Update exstraction of labels from pull request
  .github/workflows/automatic-release.yml
Labels: bug

#56 Workflow feature test
  THIS_IS_A_TEMP_FILE_FOR_WORKFLOW_TEST
Labels: feature

#57 Bug test
  THIS_IS_A_TEMP_FILE_FOR_WORKFLOW_TEST
Labels: bug

#58 Worflow breaking test
  THIS_IS_A_TEMP_FILE_FOR_WORKFLOW_TEST
Labels: breaking

#59 Worflow breaking plus others
  THIS_IS_A_TEMP_FILE_FOR_WORKFLOW_TEST
Labels: bug, feature, breaking

#60 Added skip releas for refactoring
  .github/workflows/automatic-release.yml
Labels: feature

#61 Update THIS_IS_A_TEMP_FILE_FOR_WORKFLOW_TEST
  THIS_IS_A_TEMP_FILE_FOR_WORKFLOW_TEST
Labels: refactor

#62 Updated skip relase
  .github/workflows/automatic-release.yml
Labels: refactor

#65 Updated release based on label
  .github/workflows/automatic-release.yml
Labels: refactor

#66 Updated echo to be more describtive
  .github/workflows/automatic-release.yml
Labels: refactor

#67 Fixed
  Chirp/src/SimpleDB/CsvDatabase.cs
Labels: bug

#64 Test the functionality of the csv database
  .gitignore
  .idea/.idea.Chirp.dir/.idea/projectSettingsUpdater.xml
  Chirp/.idea/.idea.Chirp/.idea/vcs.xml
  Chirp/test/Chirp.SimpleDB.Tests/Chirp.SimpleDB.Tests.csproj
  Chirp/test/Chirp.SimpleDB.Tests/CsvDatabaseTest.cs
  Chirp/test/Chirp.SimpleDB.Tests/TestObjects/CsvTestObject.cs
  Chirp/test/Chirp.SimpleDB.Tests/TestObjects/CsvTestObjectMap.cs
Labels: test

#73 Removed - 1 from elements.count when loading cheeps from the database
  Chirp/src/SimpleDB/CsvDatabase.cs
Labels: bug

#74 Added unit test and updated the integreation test
  Chirp/.idea/.idea.Chirp/.idea/vcs.xml
  Chirp/test/Chirp.SimpleDB.Tests/CsvDatabaseTest.cs
  Chirp/test/Chirp.SimpleDB.Tests/TestObjects/CsvTestObject.cs
Labels: test

#81 Refactor the csv database to a web service
  Chirp/Chirp.sln
  Chirp/data/chirp_cli_db.csv
  Chirp/src/Chirp.CLI.Client/Program.cs
  Chirp/src/Chirp.CSVDBService/Chirp.CSVDBService.csproj
  Chirp/src/Chirp.CSVDBService/Program.cs
  Chirp/src/Chirp.CSVDBService/Properties/launchSettings.json
  Chirp/src/Chirp.CSVDBService/appsettings.Development.json
  Chirp/src/Chirp.CSVDBService/appsettings.json
  Chirp/src/SimpleDB/CheepCsvDatabase.cs
Labels: feature

#84 Azure implementation
  Chirp/src/.idea/.idea.src.dir/.idea/.gitignore
  Chirp/src/.idea/.idea.src.dir/.idea/encodings.xml
  Chirp/src/.idea/.idea.src.dir/.idea/indexLayout.xml
  Chirp/src/.idea/.idea.src.dir/.idea/vcs.xml
  Chirp/src/Chirp.CLI.Client/Program.cs
  Chirp/src/Chirp.CSVDBService/.azure/config
  Chirp/src/Chirp.CSVDBService/.idea/.idea.Chirp.CSVDBService.dir/.idea/.gitignore
  Chirp/src/Chirp.CSVDBService/.idea/.idea.Chirp.CSVDBService.dir/.idea/encodings.xml
  Chirp/src/Chirp.CSVDBService/.idea/.idea.Chirp.CSVDBService.dir/.idea/indexLayout.xml
  Chirp/src/Chirp.CSVDBService/.idea/.idea.Chirp.CSVDBService.dir/.idea/vcs.xml
  Chirp/src/SimpleDB/CheepCsvDatabase.cs
Labels: bug

#87 86 handling specified limit
  Chirp/src/Chirp.CLI.Client/Program.cs
  Chirp/src/Chirp.CSVDBService/Program.cs
Labels: bug

#89 Update the build and release of workflow
  .github/workflows/automatic-release.yml
Labels: workflow

#92 Add a workflow that stops pulle request whit out a lable
  .github/workflows/check for lable.yaml
Labels: workflow

#93 Refactor workflows
  .github/workflows/automatic-release.yml
Labels: workflow

#95 Update directory azure workflow uses for publish
  .github/workflows/main_bdsa2024group10chirpremotedb.yml
  THIS_IS_A_TEMP_FILE_FOR_WORKFLOW_TEST
Labels: workflow

#96 Change workflows to run when label changes
  .github/workflows/build-and-test.yaml
  .github/workflows/check for lable.yaml
Labels: workflow

#99 Updated path and working directory
  .github/workflows/main_bdsa2024group10chirpremotedb.yml
Labels: workflow

#98 Update when action checks are runned
  .github/workflows/build-and-test.yaml
  .github/workflows/check for lable.yaml
Labels: workflow

#101 Removed push for synchronize instead
  .github/workflows/check for lable.yaml
Labels: workflow

#103 Delete THIS_IS_A_TEMP_FILE_FOR_WORKFLOW_TEST
  THIS_IS_A_TEMP_FILE_FOR_WORKFLOW_TEST
Labels: workflow

#107 106 add error handling to chirpcliclient
  Chirp/src/Chirp.CLI.Client/Program.cs
Labels: refactor

#105 Refactored to comply with naming conventions
  Chirp/src/Chirp.CLI.Client/Program.cs
Labels: refactor

#110 Convert workflow to dotnet8
  .github/workflows/automatic-release.yml
  .github/workflows/build-and-test.yaml
Labels: workflow

#111 Refactored the solution to use .NET 8
  Chirp/global.json
  Chirp/src/Chirp.CLI.Client/Chirp.CLI.Client.csproj
  Chirp/src/Chirp.CSVDBService/Chirp.CSVDBService.csproj
  Chirp/src/SimpleDB/SimpleDB.csproj
  Chirp/test/Chirp.CLI.Client.Test/Chirp.CLI.Client.Test.csproj
  Chirp/test/Chirp.CSVDBService.Test/Chirp.CSVDBService.Test.csproj
  Chirp/test/Chirp.SimpleDB.Tests/Chirp.SimpleDB.Tests.csproj
Labels: refactor

#112 Updated the url to the correct version
  Chirp/src/Chirp.CLI.Client/Program.cs
Labels: refactor

#113 Change to be on published
  .github/workflows/main_bdsa2024group10chirpremotedb.yml
Labels: workflow

#115 Added nullable value to read request to azure
  Chirp/src/Chirp.CLI.Client/Program.cs
  Chirp/src/Chirp.CSVDBService/Program.cs
Labels: breaking

#116 Update automatic-release.yml
  .github/workflows/automatic-release.yml
Labels: workflow

#117 Refactored Display method for cheep messages to make null argument display all cheeps
  Chirp/src/Chirp.CLI.Client/Program.cs
Labels: breaking

#128 Chirp CLI cleanup
  Chirp/src/Chirp.CLI.Client/Program.cs
  Chirp/src/Chirp.CSVDBService/Program.cs
  Chirp/src/SimpleDB/CsvDatabase.cs
Labels: refactor

#129 Pull neded code for test
  Chirp/Chirp.sln
  Chirp/data/chirp.db
  Chirp/data/chirp.db-journal
  Chirp/src/Chirp.Razor/CheepService.cs
  Chirp/src/Chirp.Razor/Chirp.Razor.csproj
  Chirp/src/Chirp.Razor/Pages/Public.cshtml
  Chirp/src/Chirp.Razor/Pages/Public.cshtml.cs
  Chirp/src/Chirp.Razor/Pages/Shared/_Layout.cshtml
  Chirp/src/Chirp.Razor/Pages/UserTimeline.cshtml
  Chirp/src/Chirp.Razor/Pages/UserTimeline.cshtml.cs
  Chirp/src/Chirp.Razor/Program.cs
  Chirp/src/Chirp.Razor/Properties/launchSettings.json
  Chirp/src/Chirp.Razor/appsettings.Development.json
  Chirp/src/Chirp.Razor/appsettings.json
  Chirp/src/Chirp.Razor/wwwroot/css/style.css
  Chirp/src/Chirp.Razor/wwwroot/favicon/favicon.ico
  Chirp/src/Chirp.Razor/wwwroot/images/icon1.png
  Chirp/src/SimpleDB/Cheep.cs
  Chirp/src/SimpleDB/CheepCsvDatabase.cs
  Chirp/src/SimpleDB/CheepMap.cs
  Chirp/src/SimpleDB/CsvDatabase.cs
  Chirp/src/SimpleDB/IDatabaseRepository.cs
  Chirp/src/SimpleDB/SQLiteDBFascade.cs
  Chirp/src/SimpleDB/SimpleDB.csproj
  Chirp/test/Chirp.CLI.Client.Test/Chirp.CLI.Client.Test.csproj
  Chirp/test/Chirp.CLI.Client.Test/UnitTest1.cs
  Chirp/test/Chirp.CSVDBService.Test/Chirp.CSVDBService.Test.csproj
  Chirp/test/Chirp.SimpleDB.Tests/CsvDatabaseTest.cs
Labels: refactor

#130 Pulled new needed implementation
  Chirp/.idea/.idea.Chirp/.idea/dataSources.xml
  Chirp/.idea/.idea.Chirp/.idea/sqldialects.xml
  Chirp/src/Chirp.Razor/CheepService.cs
  Chirp/src/Chirp.Razor/Chirp.Razor.csproj
  Chirp/src/SimpleDB/IDatabaseRepository.cs
  Chirp/src/SimpleDB/Model/CheepViewModel.cs
  Chirp/src/SimpleDB/SQLiteDBFascade.cs
  Chirp/src/SimpleDB/SimpleDB.csproj
Labels: refactor
