Repository ITU-BDSA2024-GROUP10/Chirp, pull requests merged in 2024-12, with the labels that each got.

#346 Domain model
  docs/models/DomainModel.drawio
Labels: documentation

#347 Created onion diagram
  docs/models/.$OnionModel.drawio.bkp
  docs/models/OnionModel.drawio
Labels: documentation

#351 About me comments
  Chirp/src/Chirp.Core/AuthorService.cs
  Chirp/src/Chirp.Core/IAuthorRepository.cs
  Chirp/src/Chirp.Infrastructure/AuthorRepository.cs
  Chirp/src/Chirp.Web/Pages/AboutMe.cshtml
  Chirp/src/Chirp.Web/Pages/AboutMe.cshtml.cs
  Chirp/src/Chirp.Web/Pages/Shared/Components/CheepList/Default.cshtml
  Chirp/test/PlaywrightTests/UITests/AboutMeTests.cs
  Chirp/test/RepositoryTests/AuthorRepositoryUnitTest.cs
Labels: code feature

#352 Made List to IEnumerable
  Chirp/src/Chirp.Core/AuthorService.cs
  Chirp/src/Chirp.Core/CheepService.cs
  Chirp/src/Chirp.Core/IAuthorRepository.cs
  Chirp/src/Chirp.Infrastructure/AuthorRepository.cs
  Chirp/src/Chirp.Web/Pages/AboutMe.cshtml
  Chirp/src/Chirp.Web/Pages/AboutMe.cshtml.cs
  Chirp/src/Chirp.Web/Pages/Shared/Components/CheepList/Default.cshtml
  Chirp/src/Chirp.Web/Pages/Shared/TimeLinePageModel.cs
  Chirp/src/Chirp.Web/Pages/SpecificCheep.cshtml.cs
  Chirp/test/RepositoryTests/AuthorRepositoryUnitTest.cs
  Chirp/test/Web.UnitTests/PageModelUnitTests.cs
Labels: refactor

#356 Digram that documents our GitHub actions
  docs/models/.$Github workflows.drawio.bkp
  docs/models/.$Github workflows.drawio.dtmp
  docs/models/Github workflows.drawio
  docs/models/WorkflowConnectionDiagram.drawio
Labels: documentation

#359 Moved files into subfolders
  docs/models/DomainModel/DomainModel.drawio
  docs/models/GithubWorkflows/.$Github workflows.drawio.bkp
  docs/models/GithubWorkflows/.$Github workflows.drawio.dtmp
  docs/models/GithubWorkflows/Github workflows.drawio
  docs/models/GithubWorkflows/WorkflowConnectionDiagram.drawio
  docs/models/Onion/.$OnionModel.drawio.bkp
  docs/models/Onion/OnionModel.drawio
Labels: documentation

#362 Document what a user can do
  docs/models/.$UserActivitiesDiagram.drawio.bkp
  docs/models/UserActivitiesDiagram.drawio
Labels: documentation

#364 Created Diagram
  docs/models/Sequence/Sequence-of-functionality.png
  docs/models/Sequence/plantuml_export.puml
Labels: documentation

#363 Login after email confirmed
  Chirp/src/Chirp.Web/Areas/Identity/Pages/Account/ConfirmEmail.cshtml
  Chirp/src/Chirp.Web/Areas/Identity/Pages/Account/ConfirmEmail.cshtml.cs
  Chirp/test/PlaywrightTests/EndToEndTests.cs
  Chirp/test/PlaywrightTests/ExternalTests.cs
Labels: feature, test

#367 Create FromIssueToMerged.drawio
  docs/models/FromIssueToMerged.drawio
Labels: documentation

#369 Created deployment diagram
  docs/models/DeploymentDiagram.drawio
Labels: documentation

#373 Updated user activity diagram
  docs/models/UserActivitiesDiagram.drawio
Labels: documentation

#374 Fix uniq email problem
  Chirp/src/Chirp.Web/Areas/Identity/Pages/Account/ExternalLogin.cshtml.cs
  Chirp/src/Chirp.Web/Areas/Identity/Pages/Account/Register.cshtml.cs
  Chirp/src/Chirp.Web/Areas/Identity/Pages/Account/RegisterConfirmation.cshtml
  Chirp/src/Chirp.Web/Areas/Identity/Pages/Account/RegisterConfirmation.cshtml.cs
  Chirp/test/PlaywrightTests/EndToEndTests.cs
  Chirp/test/PlaywrightTests/UITests/GeneralTests.cs
  Chirp/test/PlaywrightTests/Utils/PageUtils.cs
Labels: bug, test

#360 Documentation
  Chirp/src/Chirp.Core/AuthorService.cs
  Chirp/src/Chirp.Core/CheepService.cs
  Chirp/src/Chirp.Core/CustomException/UserDoesNotExist.cs
  Chirp/src/Chirp.Core/DTO/AuthorDTO.cs
  Chirp/src/Chirp.Core/DTO/CheepDTO.cs
  Chirp/src/Chirp.Core/DTO/CommentDTO.cs
  Chirp/src/Chirp.Core/DTO/LikeDTO.cs
  Chirp/src/Chirp.Core/IAuthorRepository.cs
  Chirp/src/Chirp.Core/ICheepRepository.cs
  Chirp/src/Chirp.Infrastructure/AuthorRepository.cs
  Chirp/src/Chirp.Infrastructure/CheepRepository.cs
  Chirp/src/Chirp.Infrastructure/DbInitializer.cs
  Chirp/src/Chirp.Infrastructure/Model/Author.cs
  Chirp/src/Chirp.Infrastructure/Model/Cheep.cs
  Chirp/src/Chirp.Infrastructure/Model/Comment.cs
  Chirp/src/Chirp.Infrastructure/Model/Like.cs
  Chirp/src/Chirp.Web/Pages/AboutMe.cshtml.cs
  Chirp/src/Chirp.Web/Pages/Like.cshtml.cs
  Chirp/src/Chirp.Web/Pages/Public.cshtml.cs
  Chirp/src/Chirp.Web/Pages/Shared/TimeLinePageModel.cs
  Chirp/src/Chirp.Web/Pages/SpecificCheep.cshtml.cs
  Chirp/src/Chirp.Web/Pages/UserTimeline.cshtml.cs
  Chirp/test/RepositoryTests/AuthorRepositoryUnitTest.cs
  Chirp/test/RepositoryTests/CheepRepositoryUnitTest.cs
Labels: documentation

#376 Update Login
  Chirp/src/Chirp.Web/Areas/Identity/Pages/Account/Login.cshtml
Labels: bug

#383 Report writing
  .gitignore
  LICENSE
  docs/2024_itubdsa_group_10_report.pdf
  docs/images/Deployment.png
  docs/images/DeploymentDiagram.png
  docs/images/DomainModel.png
  docs/images/FromIssueToMerged.png
  docs/images/LoggedIn.png
  docs/images/LoggedOut.png
  docs/images/OnionModel.png
  docs/images/PR_Workflow.png
  docs/images/PullRequests.png
  docs/images/ReleaseWorkflows.png
  docs/images/Sequence-of-functionality.png
  docs/images/UserActivitiesDiagram.png
  docs/images/icon1.png
  docs/images/project board.png
  docs/models/DeploymentDiagram.drawio
  docs/models/DomainModel/DomainModel.drawio
  docs/models/GithubWorkflows/Github workflows.drawio
  docs/models/GithubWorkflows/WorkflowConnectionDiagram.drawio
  docs/models/Onion/OnionModel.drawio
  docs/models/Sequence/Sequence-of-functionality.png
  docs/models/Sequence/plantuml_export.puml
  docs/models/UserActivitiesDiagram.drawio
  docs/report.md
Labels: documentation
